# Generated by Django 6.0.5 on 2026-05-25 10:04

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='ktcPlanning.project')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ktcPlanning.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_baseline', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_start', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_revisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ktcPlanning.project')),
            ],
            options={
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='ktcPlanning.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ktcPlanning.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_finish', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktcPlanning.calendar')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_versions', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ktcPlanning.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskScheduleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_start', models.DateTimeField()),
                ('early_finish', models.DateTimeField()),
                ('late_start', models.DateTimeField()),
                ('late_finish', models.DateTimeField()),
                ('total_float_hours', models.IntegerField(default=0)),
                ('free_float_hours', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('task_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ktcPlanning.taskversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_finish', models.DateTimeField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='ktcPlanning.taskversion')),
            ],
        ),
        migrations.CreateModel(
            name='WBSNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='ktcPlanning.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WBSNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ktcPlanning.wbsnode')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ktcPlanning.wbsnodeversion')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_versions', to='ktcPlanning.revision')),
            ],
            options={
                'unique_together': {('node', 'revision'), ('revision', 'parent', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='taskversion',
            name='wbs_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.wbsnodeversion'),
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='ktcPlanning.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='ktcPlanning.calendar')),
            ],
            options={
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-Start'), ('SS', 'Start-Start'), ('FF', 'Finish-Finish'), ('SF', 'Start-Finish')], default='FS', max_length=2)),
                ('lag_hours', models.IntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ktcPlanning.revision')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='ktcPlanning.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='ktcPlanning.task')),
            ],
            options={
                'unique_together': {('revision', 'predecessor', 'successor')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resource')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ktcPlanning.task')),
            ],
            options={
                'unique_together': {('revision', 'task', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='TaskRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مسئول اصلی'), ('reviewer', 'بررسی\u200cکننده'), ('executor', 'مجری'), ('project manager', 'مدیر پروژه')], max_length=20)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='ktcPlanning.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('revision', 'task', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='VarianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_variance_hours', models.IntegerField(default=0)),
                ('finish_variance_hours', models.IntegerField(default=0)),
                ('duration_variance_hours', models.IntegerField(default=0)),
                ('spi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('status', models.CharField(choices=[('on_track', 'در برنامه'), ('at_risk', 'در خطر'), ('delayed', 'تاخیر دارد')], default='on_track', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('task_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variance', to='ktcPlanning.taskversion')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='ktcPlanning_status_45c843_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taskversion',
            index=models.Index(fields=['revision', 'wbs_node'], name='ktcPlanning_revisio_46d345_idx'),
        ),
        migrations.AddIndex(
            model_name='taskversion',
            index=models.Index(fields=['planned_start'], name='ktcPlanning_planned_de6555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskversion',
            unique_together={('task', 'revision')},
        ),
    ]
