# Generated by Django 6.0.5 on 2026-05-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbsnode',
            name='level',
        ),
        migrations.RemoveField(
            model_name='wbsnode',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='wbsnode',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='wbsnode',
            name='tree_id',
        ),
    ]
